export const adPlatforms = [
  "Google Adwords",
  "Binge Ads",
  "Yahoo Gemini",
  "Taboola",
  "Facebook Adverts",
  "TikTok Ads",
  "50onRed",
  "ADAMO",
  "AdRoll",
  "AdSupply",
  "Adblade",
  "Adcash",
  "Admob",
  "Adnium",
  "Adsterra",
  "Advertise.com",
  "Airpush",
  "Amazon Ads",
  "Bidvertiser",
  "Blindclick",
  "CNET",
  "CPMOZ",
  "DNTX",
  "Dianomi",
  "DoublePimp",
  "Earnify",
  "EPOM Market",
  "Etrag.ru",
  "Exoclicks",
  "Flix Media",
  "Go2Mobi",
  "Gravity",
  "Gunggo Ads",
  "InMobi",
  "Instagram",
  "Juicy Ads",
  "Lead Impact",
  "LeadBolt",
  "LeadSense",
  "Ligatus",
  "Linkedin",
  "MGID",
  "MarketGid",
  "Media Traffic",
  "Millennial Media",
  "MoPub",
  "MobiAds",
  "NTENT",
  "Native Ads",
  "NewsCred",
  "Octobird",
  "OpenX",
  "Others",
  "Outbrain",
  "Pinterest Ads",
  "Plista",
  "Plugrush",
  "PocketMath",
  "PopAds",
  "PopCash",
  "PopMyAds",
  "Popwin",
  "Popunder.net",
  "PropelMedia",
  "Propeller Ads",
  "Qwaya Ads",
  "Rapsio",
  "RealGravity",
  "Redirect.com",
  "Recontent",
  "Revenue Hits",
  "Simple Reach",
  "Skyword",
  "SiteScout (Basis)",
  "StackAdapt",
  "StartApp",
  "SynupMedia",
  "TapSense",
  "Traffic Broker",
  "Target.my.com",
  "Traffic Factory",
  "Traffic Force",
  "Traffic Holder",
  "Traffic Junky",
  "Traffic Hunt",
  "Traflow",
  "Trellian",
  "Twitter",
  "Unity Ads",
  "Vk.com",
  "WebCollage",
  "Widget Media",
  "Yandex",
  "Zemanta",
  "ZeroPark",
  "MaxVisits",
  "Revisitors",
  "Snapchat Ads",
  "Organic Traffic",
  "Galaksion",
  "Traffic Stars",
  "Snackvideo",
];

export const fixedOptions = [
  { id: 1, label: "BUSINESS" },
  { id: 2, label: "GOVERNMENT" },
  { id: 3, label: "Wireless" },
  { id: 4, label: "ASN TS" },
  { id: 5, label: "BIPS" },
  { id: 6, label: "BOT" },
  { id: 7, label: "DATA CENTER" },
  { id: 8, label: "HRIP" },
  { id: 9, label: "ISP TS" },
  { id: 10, label: "LRIP" },
  { id: 11, label: "PROXY/VPN" },
  { id: 12, label: "TIME ZONE" },
  { id: 13, label: "TSIF" },
];

export const OPTIONS = [
  { value: "country", label: "Country" },
  { value: "state", label: "State" },
  { value: "zip", label: "Zip Code" },
  { value: "browser", label: "Browser" },
  { value: "Device", label: "Device" },
  { value: "ASN", label: "ASN" },
  { value: "referrer", label: "Referrer" },
  { value: "IP", label: "IP" },
  { value: "userAgent", label: "User Agent" },
  { value: "isp", label: "ISP" },
];
